name: Deploy Kambandu Stores
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:   
      - name: Checkout
        uses: actions/checkout@master
      - name: Use Node 16.x
        uses: actions/setup-node@master
        with:
          node-version: '16.x'
      - run: npm install --legacy-peer-deps
      - run: npm run build:prod
      - name: Deploy using ssh
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY}}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: "/var/www/store-kambandu/"


  
    


